# Generated by Django 6.0.7 on 2026-07-29 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('LIVRE', 'Livre'), ('OCUPADA', 'Ocupada')], max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='projeto.vaga')),
            ],
            options={
                'ordering': ('-criado_em',),
                'indexes': [models.Index(fields=['vaga', '-criado_em'], name='projeto_avi_vaga_id_fb72c2_idx')],
            },
        ),
    ]
