# Generated by Django 6.0.7 on 2026-07-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0003_chatmsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='pagamento',
            field=models.CharField(blank=True, choices=[('', '—'), ('SOLICITADO', 'Saída solicitada'), ('PAGO', 'Pagamento confirmado'), ('LIBERADO', 'Liberado pelo admin')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='saida_solicitada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='valor_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
