# Generated by Django 6.0.8 on 2026-08-04 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0004_veiculo_pagamento_veiculo_saida_solicitada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_contato', models.CharField(blank=True, max_length=100)),
                ('tipo', models.CharField(choices=[('ACIDENTE', 'Acidente / Colisão'), ('DANO', 'Dano ao veículo'), ('FURTO', 'Furto / Roubo'), ('VAGA', 'Problema com a vaga'), ('OUTRO', 'Outro')], max_length=15)),
                ('placa', models.CharField(blank=True, max_length=10)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('ANALISE', 'Em análise'), ('RESOLVIDO', 'Resolvido')], default='ABERTO', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-criado_em',),
            },
        ),
    ]
