# Generated by Django 6.0.8 on 2026-08-05 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0005_chamado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AVARIA', 'Avaria / Dano no Veículo'), ('ROUBO', 'Furto / Roubo'), ('COLISAO', 'Colisão / Batida'), ('CHAVEIRO', 'Problema com Chave / Tranca'), ('BRIGA', 'Desentendimento / Incidente'), ('OUTRO', 'Outro Problema')], default='OUTRO', max_length=20)),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('placa_veiculo', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em Análise'), ('RESOLVIDO', 'Resolvido')], default='PENDENTE', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projeto.vaga')),
            ],
            options={
                'ordering': ('-criado_em',),
            },
        ),
        migrations.DeleteModel(
            name='Chamado',
        ),
    ]
